#!/bin/sh

tmux has-session -t tmux_sp
if [ $? != 0 ]
then

#create the main tmux session and detach 
tmux new-session -s tmux_sp -n Main -d

#create first window
tmux send-keys -t tmux_sp

#create a new window
tmux new-window -t tmux_sp -n Aux 

#select default focus
tmux select-window -t tmux_sp:1


###########THEME############################

#split panes  border colours

#non active
tmux set -t tmux_sp pane-border-fg default
tmux set -t tmux_sp pane-border-bg default
#active
#set -t tmux_sp pane-active-border-bg '#006F95' #comment out to make pane thinner
tmux set -t tmux_sp pane-active-border-fg '#006F95'



#command line
tmux set -t tmux_sp message-fg white
tmux set -t tmux_sp message-bg black
tmux set -t tmux_sp message-attr bright



#Status-Bar
tmux set -t tmux_sp status-bg "#DDDDDD"
tmux set -t tmux_sp status-fg "#777777"
# center align window list
tmux set -t tmux_sp status-justify centre 

 
#Left side of status bar
tmux set -t tmux_sp status-left-length 500
tmux set-option -t tmux_sp status-left  '#[fg=#ffffff]'
#right side of status bar
tmux set -t tmux_sp status-right-length 500
tmux set-option -t tmux_sp status-right '#[fg=#ffffff]'




####window properties


###Win1

# Current or active window in status bar
tmux set -t tmux_sp:1 window-status-current-attr bold
tmux set -t tmux_sp:1 window-status-current-fg white
tmux set -t tmux_sp:1 window-status-current-bg '#0099CC'
# Non active window in status bar
tmux set -t tmux_sp:1 window-status-attr bold
tmux set -t tmux_sp:1 window-status-fg black
tmux set -t tmux_sp:1  window-status-bg '#828282'

###Win2
tmux set -t tmux_sp:2 window-status-current-attr bold
tmux set -t tmux_sp:2 window-status-current-fg white
tmux set -t tmux_sp:2 window-status-current-bg '#0099CC'
tmux set -t tmux_sp:2 window-status-attr bold
tmux set -t tmux_sp:2 window-status-fg black
tmux set -t tmux_sp:2  window-status-bg '#828282'


#clear annoying window flags
tmux set  -t tmux_sp:1  window-status-current-format " #I$ #W"
tmux set  -t tmux_sp:2  window-status-current-format " #I$ #W"

tmux set -t tmux_sp:1    window-status-format " #I$ #W "
tmux set -t tmux_sp:2    window-status-format " #I$ #W "




fi

tmux attach -t tmux_sp
