#!/bin/sh

#to not launch if already running
tmux has-session -t tmux_mpd
if [ $? != 0 ]
then

#create the main tmux session and detach 
tmux new-session -s tmux_mpd -n Player -d

#create first window
tmux send-keys -t tmux_mpd 'ncmpcpp' C-m
#split that window vert
tmux split-window -v -t tmux_mpd
#focus on that split and execute lyvi
tmux send-keys -t tmux_mpd:1.2 'lyvi' C-m

#split the botom into 2 horizontoly 
tmux split-window -h -t tmux_mpd
#focus on right split now and execute alsamixer
tmux send-keys -t tmux_mpd:1.3 'export PS1=""; clear' C-m

tmux split-window

tmux send-keys  -t tmux_mpd:2.1 'alsamixer' C-m
#split that window vert
tmux split-window -v -t tmux_mpd
#focus on that split and execute lyvi
tmux send-keys -t tmux_mpd:2.2 'pacmixer' C-m


#create a new window 3
tmux new-window -t tmux_mpd -n Tag 
tmux send-keys  -t tmux_mpd:3.1 'mpc' C-m

#create a new window 4
tmux new-window -t tmux_mpd -n Extra 
tmux send-keys  -t tmux_mpd:4.1 'mpc' C-m

#select default focus
tmux select-window -t tmux_mpd:1

###########THEME############################

#split panes  border colours

#non active
tmux set -t tmux_mpd pane-border-fg default
tmux set -t tmux_mpd pane-border-bg default
#active
set -t tmux_mpd pane-active-border-bg '#FFFFFFF' #comment out to make pane thinner
tmux set -t tmux_mpd pane-active-border-fg '#006F95'



#command line
tmux set -t tmux_mpd message-fg white
tmux set -t tmux_mpd message-bg black
tmux set -t tmux_mpd message-attr bright



#Status-Bar
tmux set -t tmux_mpd status-bg "#222222"
tmux set -t tmux_mpd status-fg "#777777"
# center align window list
tmux set -t tmux_mpd status-justify centre 

 
#Left side of status bar
tmux set -t tmux_mpd status-left-length 500
tmux set-option -t tmux_mpd status-left  '#[fg=#ffffff]Track#(/usr/bin/mpc current -f "%%track%%")(#(/usr/bin/mpc current -f "%%time%%"))'
#right side of status bar
tmux set -t tmux_mpd status-right-length 500
tmux set-option -t tmux_mpd status-right '#[fg=#ffffff]#(/usr/bin/mpc current -f "%%title%%-%%album%% \(%%artist%%")) '




####window properties


###Win1

# Current or active window in status bar
tmux set -t tmux_mpd:1 window-status-current-attr bold
tmux set -t tmux_mpd:1 window-status-current-fg white
tmux set -t tmux_mpd:1 window-status-current-bg '#0099CC'
# Non active window in status bar
tmux set -t tmux_mpd:1 window-status-attr bold
tmux set -t tmux_mpd:1 window-status-fg black
tmux set -t tmux_mpd:1  window-status-bg '#828282'

###Win2
tmux set -t tmux_mpd:2 window-status-current-attr bold
tmux set -t tmux_mpd:2 window-status-current-fg white
tmux set -t tmux_mpd:2 window-status-current-bg '#0099CC'
tmux set -t tmux_mpd:2 window-status-attr bold
tmux set -t tmux_mpd:2 window-status-fg black
tmux set -t tmux_mpd:2  window-status-bg '#828282'

###Win3
tmux set -t tmux_mpd:3 window-status-current-attr bold
tmux set -t tmux_mpd:3 window-status-current-fg white
tmux set -t tmux_mpd:3 window-status-current-bg '#0099CC'
tmux set -t tmux_mpd:3 window-status-attr bold
tmux set -t tmux_mpd:3 window-status-fg black
tmux set -t tmux_mpd:3  window-status-bg '#828282'


###Win4
tmux set -t tmux_mpd:4 window-status-current-attr bold
tmux set -t tmux_mpd:4 window-status-current-fg white
tmux set -t tmux_mpd:4 window-status-current-bg '#0099CC'
tmux set -t tmux_mpd:4 window-status-attr bold
tmux set -t tmux_mpd:4 window-status-fg black
tmux set -t tmux_mpd:4  window-status-bg '#828282'


#clear annoying window flags
tmux set  -t tmux_mpd:1  window-status-current-format " #I$ #W"
tmux set  -t tmux_mpd:2  window-status-current-format " #I$ #W"
tmux set  -t tmux_mpd:3  window-status-current-format " #I$ #W"
tmux set  -t tmux_mpd:4  window-status-current-format " #I$ #W"

tmux set -t tmux_mpd:1    window-status-format " #I$ #W "
tmux set -t tmux_mpd:2    window-status-format " #I$ #W "
tmux set -t tmux_mpd:3    window-status-format " #I$ #W "
tmux set -t tmux_mpd:4    window-status-format " #I$ #W "


fi

tmux attach -t tmux_mpd
