#!/bin/bash

while true; do
        ping -c 1 www.google.com > /dev/null 2>&1
        if [ "$?" -eq 0 ]; then
                pgrep dropbox*
                if [ "$?" -eq 1 ]; then
                        dropboxd > /dev/null 2>&1
                fi
        fi
        sleep 2 > /dev/null 2>&1
done
