#!/bin/sh

tmux has-session -t tmux_office
if [ $? != 0 ]
then

#create the main tmux session and detach 
tmux new-session -s tmux_office -n task_console -d

#create first window
tmux send-keys -t tmux_office 'clear; task next' C-m


:#create a new window 2
tmux new-window -t tmux_office -n Projects 
#split that window vert
tmux split-window -v -t tmux_office
tmux split-window -h -t tmux_office:2.2
tmux split-window -h -t tmux_office:2.1

#launch apps
tmux send-keys  -t tmux_office:2.1 '/home/zeltak/bin/taskViewer_nix'  C-m
tmux send-keys -t tmux_office:2.2  '/home/zeltak/bin/taskViewer_uni'   C-m
tmux send-keys -t tmux_office:2.3  '/home/zeltak/bin/taskViewer_dl' C-m
tmux send-keys -t tmux_office:2.4  '/home/zeltak/bin/taskViewer_home'  C-m




#create a new window 3
tmux new-window -t tmux_office -n Vit 
tmux send-keys  -t tmux_office:3.1 'vit' C-m

#select default focus
tmux select-window -t tmux_office:1


###########THEME############################

#split panes  border colours

#non active
tmux set -t tmux_office pane-border-fg default
tmux set -t tmux_office pane-border-bg default
#active
#set -t tmux_office pane-active-border-bg '#006F95' #comment out to make pane thinner
tmux set -t tmux_office pane-active-border-fg '#006F95'



#command line
tmux set -t tmux_office message-fg white
tmux set -t tmux_office message-bg black
tmux set -t tmux_office message-attr bright



#Status-Bar
tmux set -t tmux_office status-bg "#DDDDDD"
tmux set -t tmux_office status-fg "#777777"
# center align window list
tmux set -t tmux_office status-justify centre 

 
#Left side of status bar
tmux set -t tmux_office status-left-length 500
tmux set-option -t tmux_office status-left  '#[fg=#ffffff]'
#right side of status bar
tmux set -t tmux_office status-right-length 500
tmux set-option -t tmux_office status-right '#[fg=#ffffff]'




####window properties


###Win1

# Current or active window in status bar
tmux set -t tmux_office:1 window-status-current-attr bold
tmux set -t tmux_office:1 window-status-current-fg white
tmux set -t tmux_office:1 window-status-current-bg '#0099CC'
# Non active window in status bar
tmux set -t tmux_office:1 window-status-attr bold
tmux set -t tmux_office:1 window-status-fg black
tmux set -t tmux_office:1  window-status-bg '#828282'

###Win2
tmux set -t tmux_office:2 window-status-current-attr bold
tmux set -t tmux_office:2 window-status-current-fg white
tmux set -t tmux_office:2 window-status-current-bg '#0099CC'
tmux set -t tmux_office:2 window-status-attr bold
tmux set -t tmux_office:2 window-status-fg black
tmux set -t tmux_office:2  window-status-bg '#828282'

###Win3
tmux set -t tmux_office:3 window-status-current-attr bold
tmux set -t tmux_office:3 window-status-current-fg white
tmux set -t tmux_office:3 window-status-current-bg '#0099CC'
tmux set -t tmux_office:3 window-status-attr bold
tmux set -t tmux_office:3 window-status-fg black
tmux set -t tmux_office:3  window-status-bg '#828282'


#clear annoying window flags
tmux set  -t tmux_office:1  window-status-current-format " #I$ #W"
tmux set  -t tmux_office:2  window-status-current-format " #I$ #W"
tmux set  -t tmux_office:3  window-status-current-format " #I$ #W"

tmux set -t tmux_office:1    window-status-format " #I$ #W "
tmux set -t tmux_office:2    window-status-format " #I$ #W "
tmux set -t tmux_office:3    window-status-format " #I$ #W "



fi

tmux attach -t tmux_office

