#!/bin/bash

# this is a simple config for herbstluftwm

function hc() {
    herbstclient "$@"
}

hc emit_hook reload

#xsetroot -solid '#5A8E3A'


# remove all existing keybindings
hc keyunbind --all

# keybindings
herbstclient pad 0 0 0 25 0

Mod=Mod4
hc keybind $Mod-z floating toggle
hc keybind $Mod-Shift-q quit
hc keybind $Mod-Shift-r reload
hc keybind $Mod-k close
hc keybind $Mod-Return spawn termite --role=term /bin/zsh
hc keybind $Mod-Shift-Return spawn termite /bin/zsh
hc keybind Print spawn teiler
hc keybind $Mod-Shift-s spawn termite --role=ssh -e karif
hc keybind $Mod-Shift-F12 spawn lastfm.sh switch
hc keybind $Mod-F12 spawn lastfm.sh check
hc keybind $Mod-Shift-F11 spawn love
hc keybind $Mod-Tab cycle_all 
hc keybind $Mod-F1 jumpto urgent
hc keybind $Mod-Shift-F1 bring urgent



# tags
    TAG_NAMES=( {main,terms,www,Mmedia,IM,FM,SSH,Org,Emacs,misc,Utils,Tviewer} )
    TAG_KEYS=( {grave,1,2,3,4,q,w,e,a,s,d,z}  )

    hc rename default "${TAG_NAMES[0]}" || true
    for i in ${!TAG_NAMES[@]} ; do
        hc add "${TAG_NAMES[$i]}"
        key="${TAG_KEYS[$i]}"
        if ! [ -z "$key" ] ; then
            hc keybind "$Mod-$key"       use  "${TAG_NAMES[$i]}"
            hc keybind "$Mod-Shift-$key" move "${TAG_NAMES[$i]}"
        fi
    done

# cycle through tags
hc keybind $Mod-period use_index +1 --skip-visible
hc keybind $Mod-comma  use_index -1 --skip-visible
hc keybind $Mod-Right focus right
hc keybind $Mod-Left focus left
hc keybind $Mod-Up focus up
hc keybind $Mod-Down focus down
hc keybind $Mod-Shift-Right shift right
hc keybind $Mod-Shift-Left shift left
hc keybind $Mod-Shift-Up shift up
hc keybind $Mod-Shift-Down shift down

# layouting
hc keybind $Mod-r remove
hc keybind $Mod-space cycle_layout 1
hc keybind $Mod-v split vertical 0.5
hc keybind $Mod-h split horizontal 0.5
hc keybind $Mod-Shift-v split vertical 0.3
hc keybind $Mod+Shift+h split horizontal 0.3
hc keybind $Mod-s floating toggle
hc keybind $Mod-f fullscreen toggle
hc keybind $Mod-Shift-p pseudotile toggle

# resizing
RESIZESTEP=0.05
hc keybind $Mod-Control-Left resize left +$RESIZESTEP
hc keybind $Mod-Control-Down resize down +$RESIZESTEP
hc keybind $Mod-Control-Up resize up +$RESIZESTEP
hc keybind $Mod-Control-Right resize right +$RESIZESTEP

# mouse
hc mouseunbind --all
hc mousebind $Mod-Button1 move
hc mousebind $Mod-Button2 resize
hc mousebind $Mod-Button3 zoom

# focus
#hc keybind $Mod-BackSpace   cycle_monitor
#hc keybind $Mod-Tab         cycle_all +1
#hc keybind $Mod-Shift-Tab   cycle_all -1
hc keybind $Mod-c cycle
hc keybind $Mod-i jumpto urgent
hc keybind $Mod-KP_Left shift left
hc keybind $Mod-KP_Down shift down
hc keybind $Mod-KP_Right shift right
hc keybind $Mod-KP_Up shift up

# colors
hc set default_frame_layout max
hc set frame_border_active_color '#82B414'
hc set frame_border_normal_color '#0c0d0e'
hc set frame_bg_normal_color '#121212'
hc set frame_active_opacity 90
hc set frame_normal_opacity 70
hc set frame_bg_active_color '#121212'
hc set frame_bg_transparent 1
hc set frame_border_width 0
hc set window_border_inner_width 0
hc set window_border_width 5
hc set window_border_normal_color '#454545'
hc set window_border_active_color '#0c73c2'
hc set always_show_frame 1
hc set frame_gap 0
# add overlapping window borders
hc set window_gap 8
hc set frame_padding -3
hc set window_padding 0
hc set smart_window_surroundings 0

hc set smart_frame_surroundings 1
hc set mouse_recenter_gap 0
hc set focus_follows_mouse 0
hc set raise_on_focus 1
#hc pad 5 5 5 5 5

# rules
hc unrule -F
#hc rule class=XTerm tag=3 # move all xterms to tag 3
hc rule focus=on # normally do not focus new clients
# give focus to most common terminals
hc rule class~'(.*[Rr]xvt.*|.*[Tt]erm|Konsole)' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(DIALOG|UTILITY|SPLASH)' pseudotile=on
hc rule windowtype='_NET_WM_WINDOW_TYPE_DIALOG' focus=on
hc rule windowtype~'_NET_WM_WINDOW_TYPE_(NOTIFICATION|DOCK)' manage=off
hc rule class=Firefox tag=www
hc rule class=Chromium tag=www
hc rule windowrole=term tag=terms
hc rule windowrole=ssh tag=terms
hc rule class=Transmission-remote-gtk tag=dl
hc rule class=Doublecmd tag=FM


hc rule instance=main_term tag=terms
hc rule instance=tmux_mpd tag=Mmedia
hc rule instance=skype    tag=IM
hc rule instance=Pavucontrol  tag=IM
hc rule instance=ssh_karif  tag=SSH
hc rule instance=tmux_utils  tag=Utils












# unlock, just to be sure
hc unlock

herbstclient set tree_style '╾│ ├└╼─┐'

# do multi monitor setup here, e.g.:
# hc set_monitors 1280x1024+0+0 1280x1024+1280+0
# or simply:
# hc detect_monitors

# find the panel
panel=~/.config/herbstluftwm/panel.sh
[ -x "$panel" ] || panel=$HOME/.config/herbstluftwm/panel.sh
for monitor in $(herbstclient list_monitors | cut -d: -f1) ; do
    # start it on each monitor
    $panel $monitor &
done

# GIMP
# ensure there is a gimp tag
hc load gfx '
(split horizontal:0.850000:0
  (split horizontal:0.200000:1
    (clients vertical:0)
    (clients grid:0))
  (clients vertical:0))
'               # load predefined layout
# center all other gimp windows on gimp tag
hc rule class=Gimp tag=gfx index=01 pseudotile=on
hc rule class=Gimp windowrole~'gimp-(image-window|toolbox|dock)' \
    pseudotile=off
hc rule class=Gimp windowrole=gimp-toolbox focus=off index=00
hc rule class=Gimp windowrole=gimp-dock focus=off index=1
